// <auto-generated />
using System;
using Asee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asee.Migrations
{
    [DbContext(typeof(FeeDbContext))]
    [Migration("20250801130937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Asee.Models.Domain.FeeRules", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId");

                    b.ToTable("FeeRules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleId = "1",
                            Action = "fixed_fee",
                            Amount = 0.2m,
                            Criteria = "{\"maxAmount\": 100}",
                            Description = "Fixed fee for POS transactions",
                            IsActive = true,
                            RuleType = "POS"
                        },
                        new
                        {
                            RuleId = "2",
                            Action = "percentage_fee",
                            Amount = 0.18m,
                            Criteria = "{\"minAmount\": 10}",
                            Description = "Percentage fee for e-commerce transactions",
                            IsActive = true,
                            RuleType = "E-commerce"
                        });
                });

            modelBuilder.Entity("Asee.Models.Entities.FeeCalculationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeeCalculationHistory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
